[features]
seeds = false
skip-lint = false
[programs.localnet]
raw_transfer = "DG5JkWNFNmU7ebXkE9gc9wRF1N5ynd7AjyDBww5NJHRf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tristan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
